test:
  image: node:lts-alpine
  stage: test
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
  script:
    - npm install
    - npx eslint src
    - CI=true npm run test
    - npm prune

.buildTemplate: &buildTemplate
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo $TAG
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$TAG
      --destination $CI_REGISTRY_IMAGE:latest

dockerBuildSHA:
  <<: *buildTemplate
  only:
    - develop
  variables:
    TAG: "$CI_COMMIT_SHORT_SHA"

dockerBuildTAG:
  <<: *buildTemplate
  only:
    - tags
  variables:
    TAG: "$CI_COMMIT_TAG"

deploy:
  image:
    name: alpine/helm:3.1.0
    entrypoint:
      - ""
  stage: deploy
  only:
    - develop
  script:
    - mkdir -p $HOME/.kube
    - echo $KUBE_CONFIG | base64 -d > $HOME/.kube/config
    - helm upgrade
      --install
      --namespace default
      --set imagePullSecrets[0].name=regcred-gitlab
      --set image.repository=$CI_REGISTRY_IMAGE
      --set image.tag=$CI_COMMIT_SHORT_SHA
      --history-max 2
      express-starter
      ./helm
